### ISSUE TITLE
Gamepad code breaks webpage

### ISSUE THREAD

**Issue by Scuffward** [FrostKiwi/Mirrorball#15]
If the user has a gamepad plugged in that does not have a button index 14, the web page crashes when trying to load media.

Uncaught TypeError: Cannot read properties of undefined (reading 'pressed')
    at Ct (index-8efaa98d.js:612:13377)
    at i (index-8efaa98d.js:612:17012)

**Comment by FrostKiwi** [comment]
> If the user has a gamepad plugged in that does not have a button index 14, the web page crashes when trying to load media.
> 
> Uncaught TypeError: Cannot read properties of undefined (reading 'pressed') at Ct (index-8efaa98d.js:612:13377) at i (index-8efaa98d.js:612:17012)

The offending line is probably here: https://github.com/FrostKiwi/Mirrorball/blob/cf70f27cdee9489a532623714922c4f44b7e9467/src/js/input.js#L104

I'll see how to handle this better.

**Comment by FrostKiwi** [comment]
Yeah, there are no clever solutions to this. You can't read out the mapping due to browser fingerprinting rules.
Implementing the Fix with a assign Gamepad Controls interface.

Temp-fixed for the time being by checking for the existence of that button object

**Comment by FrostKiwi** [comment]
@Scuffward A new Gamepad mapping interface is now implemented. All gamepad inputs are unmapped by default and when a new gamepad is connected, the interface opens up, where users can map their controls.
![image](https://github.com/FrostKiwi/Mirrorball/assets/60887273/5612fb97-d4bd-4564-a7ad-bec2d34bd714)
The menu can also be re-opened in the settings tab of the controls. It cannot be opened if no controller is connected.
