### ISSUE TITLE
Literal mirror ball: The kilogram

### ISSUE THREAD

**Issue by BenBE** [FrostKiwi/Mirrorball#19]
Veritasium had a video on the kilogram:

https://www.youtube.com/watch?v=ZMByI4s-D-Y

There are several good shots of that ideal sphere, e.g.:
![image](https://github.com/user-attachments/assets/5a7292ae-2596-4d38-8a29-cb4383422e04)

![image](https://github.com/user-attachments/assets/100f4c0d-f5a9-4548-aecc-1d01c793b0e7)
![image](https://github.com/user-attachments/assets/e2d1d761-ee21-4a26-af01-ba8544abc1c8)

**Comment by FrostKiwi** [comment]
Really good catch! Added it as a user Submission under your username: https://mirrorball.frost.kiwi/?path=/media_user/veritasium.jpg&menu=false
It's really interesting how you can see Derek and Ms. Katie Green projected, as they stand behind the mirror ball

![image](https://github.com/user-attachments/assets/87bff1bf-5542-4de9-9d90-31beff6eabe0)
